# Generated by Django 4.1.1 on 2022-09-22 08:14

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('target', models.PositiveIntegerField(verbose_name='Нужная сумма')),
                ('progress', models.PositiveIntegerField(verbose_name='Собранные средства')),
                ('charityQty', models.PositiveIntegerField(verbose_name='Спонсоры')),
                ('city', models.CharField(max_length=40, verbose_name='Город')),
                ('owner', models.CharField(max_length=40, verbose_name='ФИО Получателя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Tелефон')),
                ('creation_date', models.DateField(verbose_name='Дата создания')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('requisites', models.CharField(max_length=255, verbose_name='Реквизиты')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-id', '-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категории')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_images', to='donation.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='categoryId',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation', to='donation.category'),
        ),
    ]
