# Generated by Django 4.0.7 on 2022-09-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_article_is_active_alter_article_categoryid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Donation',
        ),
    ]
