# Generated by Django 4.0.7 on 2022-09-22 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_rename_article_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='city',
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True, verbose_name='Город')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='donation.donation')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Город',
            },
        ),
    ]
