# Generated by Django 4.0.7 on 2022-09-22 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_remove_donation_city_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Городa', 'verbose_name_plural': 'Городa'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='donation',
        ),
        migrations.AddField(
            model_name='donation',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='donation.city', verbose_name='Город'),
        ),
    ]
