# Generated by Django 4.0.7 on 2022-09-23 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_alter_city_options_remove_city_donation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='DonationImage',
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='donation.category')),
            ],
        ),
    ]
