# Generated by Django 4.0.7 on 2022-09-23 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_rename_image_donationimage_categoryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
