# Generated by Django 4.0.7 on 2022-09-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='salt',
        ),
    ]
